print ("How old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input()
print("How heavy are you?", end=' ')
weight = input()
print(f"So, you're {age} old, {height} tall and {weight} heavy.")

print("Hey buddy, how ya feelin?", end=' ')
vibe = input()
print(f"Feeling pretty {vibe}, are ya? I feel it sometimes, too.")